data <- read.table('./household_power_consumption.txt',header = TRUE,sep=';',colClasses='character')
data <- subset(data, data$Date == '1/2/2007' | data$Date == '2/2/2007')
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)
data$Time<-strptime(paste0(data$Date, data$Time), '%d/%m/%Y %H:%M:%S')
png('plot3.png', width=480, height=480)
plot(data$Time, data$Sub_metering_1, type='l', xlab = '', ylab = 'Energy sub metering')
lines(data$Time, data$Sub_metering_2, col = 'red')
lines(data$Time, data$Sub_metering_3, col = 'blue')
legend('topright', c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), col = c(1,2,4), pch='_')
dev.off()